### ISSUE TITLE
Historie umístění

### ISSUE THREAD

**Issue by Aidam** [Clevis/ReKola-Public#1]
(asi spíš feature-request) 
Při selhání lokalizace/zadávání adresy by se hodila historie - je to precejen pruda vytukavat "U Zeměpisného ústavu 1" víc než jednou

**Comment by VitekJezek** [comment]
Matěj (zodpovědný frontend) povídal, že má nějaké řešení v hlavě. Na druhou stranu myslím, že doimplementovat to hlášení / řešení problémů má větší důležitost...

Jinak ty máš jaký telefon (verzi OS / browseru), že ta lokalizace selhává?

**Comment by Aidam** [comment]
mam android 4.0.3 na HTC ONE V. a souhlasim že hlášení problémů má vyšší prioritu.
