### ISSUE TITLE
Kolo #973

### ISSUE THREAD

**Issue by tomkukral** [Clevis/ReKola-Public#101]
Ahoj,
opsal jsem špatně kód kola a omylem jsem si půjčil jiné. Nemůžu ho ted vratit na správné místo, protože nevím kde bylo. 

Bylo by možné prosím zrušit mé aktuální půjčení kola (#973)? Nebo mi prosím poraďte jak to mám vyřešit.

**Comment by radekbernatek** [comment]
Ahoj,
tak kolo už bys půjčené mít neměl. Můžu se jen zeptat jak se ti povedlo opsat kód jiného kola? Abysme případně nějak prověřili jestli se to nemůže stát i někomu jinému...

Jinak příště možná radši využij nahlášení issue přímo přes aplikaci, zpracování bude určitě rychlejší ;-)

**Comment by Piskvor** [comment]
Úplně jednoduše: místo blbě čitelný sedmičky opíšeš jedničku, nebo místo trojky osmičku, nebo tak něco - a trefíš se do jinýho, existujícího kódu (10^6 kombinací není zase tolik, při dostatečném počtu pokusů ten jackpot prostě někdo vyhraje). Ostatně, mně se to kdysi povedlo taky: https://github.com/Clevis/ReKola-Public/issues/70

**Comment by radekbernatek** [comment]
Tady by to byla ale velká náhoda myslím, verifikační kody se shodují jen na 3 pozici - 609089 x 169724.

**Comment by tomkukral** [comment]
No jednoduše, protože jsem idiot   ...
Vracel jsem kolo, napsal popisek a když jsem klikal na vrátit, tak jsem si pohnul mapou, takže jsem ho vrátil na špatné místo (o cca 100m). Chtěl jsem to napravit tím, že si ho znovu půjčím&vrátím a tím to opravím ... ale byl jsem už v tramvaji a myslel jsem si, že si číslo kola pamatuju. 
Spletl jsem si číslo s číslem jiného kola a už nebyla cesta zpátky.

Díky za vyřešení, přístě si na to dám větší pozor.
