### ISSUE TITLE
GPS tracking pohybu + statistiky

### ISSUE THREAD

**Issue by HonzaaD** [Clevis/ReKola-Public#106]
Na strance https://www.rekola.cz/podminky jsem se docetl, ze nektera kola maji GPS chipy a nebo ze si vlasne muzu na mobilu zapnout tracking pohybu (v aplikaci jsem tuto moznost zatim nenasel). Bylo by super, kdyby tyto statistiky byli uzivatelsky pristupne a kdyby se toto v komunite vyuzilo napriklad k nejake gamefikaci a zebrickum nejaktivnejsich uzivatelu... :) 

Napriklad bych uvital nejake statistiky kolik sem s jakym kolem stravil casu jak casto si kola pujcuji atd.

**Comment by zbycz** [comment]
Základní statistiky by se měly objevit v horizontu jednoho týdne. Ovšem jak sis všiml aplikace zatím zaznamenává jen pozici půjčení a vrácení, tedy bude to čistě orientační. Samozřejmě když kolo budeš vracet v aplikaci při každé zastávce, bude to přesnější a zároveň si ho můžou půjčit další :-)

**Comment by HonzaaD** [comment]
Tak super, uz se tesim. A ano, zatim to tak delam, kolo si nenechavam a vzdy kdyz nekam prejedu, tak ho vratim, ikdyz me uz moc nebavi stale dokola opisovat to sestimistne cislo (zatim jezdim jen tri dny), idealni by to bylo pres ten QR kod, prijdu namirim fotak automaticky se kolo zapujci, nemusel bych nic opisovat a na nic klikat. To by bylo hodne luksusni.. :)

**Comment by zbycz** [comment]
Ano, tak to v podstatě dělám taky. 

Pokud bys věděl o někom kdo umí programovat Android aplikace - klidně tam může QR půjčení doprogrmovat. Pak je to jen otázka vylepení samolepek (+ odladění velikostí). Zdrojáky aplikace jsou v [Rekolacz/mobile-android](//github.com/Rekolacz/mobile-android)

**Comment by HonzaaD** [comment]
Aha, ja bych to spise potreboval na iOS, ale ok.

**Comment by zbycz** [comment]
IOS appka je také na github.com/Rekolacz - stačí přesvědčit někoho, kdo to umí, aby to udělal. Nebo počkat a třeba to časem bude :-)
