### ISSUE TITLE
Při vracení se v aplikaci často zasekne mapka - Android

### ISSUE THREAD

**Issue by michaljuris** [Clevis/ReKola-Public#108]
Při vracení se v aplikaci často zasekne mapka - nejde s ní hnout a tedy upřesnit polohu vraceného kola.

Pomůže až "kill" a restart aplikace.

HTC One M7, Android 5.0.2

**Comment by zbycz** [comment]
Potvrzuji, též Android 4.0.4. Píšeme do seznamu issue.

**Comment by michaljuris** [comment]
Odpozoroval jsem kdy se objevuje chyba:

Kdykoliv se za běhu aplikace (možná jen kdykoliv v době zapůjčení - to nemám ověřeno) přepnu do mapky s umístěním kol, tak při vracení s mapkou nejde hlídat.
Pokud se do mapy nepodívám, při vracení s mapkou hýbat jde - ověřeno.

Díky za opravu.

P.S.: zaslouží si tato chybka skutečně label "neprioritní"?

**Comment by michaljuris** [comment]
v nové verzi se zdá být opraveno
