### ISSUE TITLE
Android 2.2.2: Vytuhnuti prohlizece pri zadavani kodu kola

### ISSUE THREAD

**Issue by kubahorak** [Clevis/ReKola-Public#11]
Mam Android 2.2.2 a pouzivam vychozi webovy prohlizec. Kdyz si chci pujcit kolo podle kodu, zacnu do policka pro kod zadavat cislice a prohlizec mi po nekolika cislicich vytuhne. Pak musim restartovat prohlizec. V procesech vidim, ze si prohlizec bere hodne pameti, 20-25MB a to muj staricky telefon nedava.

Neslo by udelat formular pro zadavani kodu s mensim pouzitim Javascriptu? Mozna nejaka validace onchange nebo neco takoveho prohlizec vytezuje. Javascript si zere pamet a to se memu telefonu nelibi. Idealni by byl formular bez Javascriptu.

**Comment by enzy** [comment]
Bohužel Andorid 2.2 nepodprorujeme, ale pokusím se na to ve volné chvíli podívat (nebude to bohužel brzo - min. týden/14dní).

**Comment by kubahorak** [comment]
Vyzkouseno i v Dolphin Browser Mini a tentyz problem. Aplikace vytuhne pri zadavani kodu.

**Comment by washeck** [comment]
A co Android 2.3.5, podporujete? Na HTC Wildfire S  aplikace dost zlobí. Na přihlašovací obrazovce je problém zadat heslo (kurzor odskočí někam nahoru, kde předtím bylo pole pro login), občas problikne přihlašovací obrazovka i když jsem už přihlášený, u nepojízdného kola červený varovný pruh odsune zbytek stránky dolů, takže z tlačítka "Problémy" vidím jen horní čast.

**Comment by kubahorak** [comment]
Mohu potvrdit, ze na malem displeji se nevejde detail kola na obrazovku. V prohlizeci nefunguje scrollovani.

**Comment by enzy** [comment]
Pracuje se na tom

**Comment by enzy** [comment]
@kubahorak mohl by jsi prosím vyzkoušet opravu na naší DEV verzi? http://rekola.clevis.org

Kódy ke kolům:

```
Emtébéčkox 1234
Babokolo 4321
Silnička 5678
Rozkládačka 8765
```

Díky!

**Comment by enzy** [comment]
Nová verze nasazena a na testovacích zařízeních (i 2.2) už se aplikace chová normálně. Zavírám tedy.

**Comment by kubahorak** [comment]
Vyzkouseno na ostre a scrollovani funguje. Aplikace jiz take nevytuhava pri zadavani kodu kola. Diky!
