### ISSUE TITLE
HTTP 500 pri pouziti voucheru z DPNK

### ISSUE THREAD

**Issue by washeck** [Clevis/ReKola-Public#110]
Měl jsem účet z první sezóny Rekol v Praze, loni jsem neplatil. Letos jsem chtěl využít voucher z Do práce na kole.
1. Přihlásím se do Rekola.cz
2. Prodloužit členství (https://www.rekola.cz/ucet/profile/extend-membership)
3. Zvolím Chci uplatnit dárkový poukaz a zadám svůj kód (vx.....7jq)
4. Aplikace vyhodí 500 na adrese https://www.rekola.cz/ucet/profile/extend-membership?do=extendMembershipForm-submit

(Pokud zadám neplatný kód, třeba "test", aplikace správně řekne "Uvedené číslo poukazu nebylo nalezeno.")

**Comment by zbycz** [comment]
@honzasladek

**Comment by honzasladek** [comment]
@washeck Včera jsme tam něco opravovali, mělo by to teď fungovat. // cc @zbycz

**Comment by washeck** [comment]
Potvrzuju, ze uz je to OK.
