### ISSUE TITLE
Login potřeba příliš často (?)

### ISSUE THREAD

**Issue by Aidam** [Clevis/ReKola-Public#13]
Nevim jestli se to už nezměnilo s nějakou novějí verzí, ale přišlo mi, že se musím přihlašovat při každém spuštění - to snad není nutně potřeba

**Comment by VaclavSir** [comment]
Nepodařilo se mi přijít na to, čím to je, přihlášení by mělo vydržet 30 dní.

**Comment by VitekJezek** [comment]
hmm, taky jsem měl pocit, že se mi appka odhlašuje, ale už se mi to nedělá.

Ono tedy pozor! Jeden login je aktivní jen na jednom zařízení, tedy tento workflow je korektní (i z důvodu bezpečnosti):
- přihlášení na telefonu A
- přihlášení na telefonu B
- uživatel ztratil přihlášení na telefonu A, přihlásí se zde znovu
- ale tím zas ztratil přihlášení na B, musí se přihlásit znovu
- and so on...

@Aidam - dělá ti to i jinak? (bál jsem se toho, že bys ztratil login, kdybys přecházel z wifi na GSM a zpět. Ale teď jsem to vyzkoušel a to drží).

Případně - můžeš to prosím zavřít?

**Comment by enzy** [comment]
Pokoušel jsem se to debugnout a nenalezl jsem kde to selhává. Faktem však je, že Andorid 2.x se při obnově stránky "zasekne" na přihlášení, i když se provedou všechny následující kroky (geolokace, získání seznamu kol, jejich výpis na pozadí).
