### ISSUE TITLE
Info o verzi / changelog pro testery

### ISSUE THREAD

**Issue by Aidam** [Clevis/ReKola-Public#14]
Myslim, že by se hodilo pro nás testující jednak kdybychom nějak poznali, že proběhly úpravy a taky kdyby byl nějakej changelog, abychom viděli na co se zaměřit.

**Comment by enzy** [comment]
@VitekJezek co takhle zneužít github releases? Zjednodušeně to je markdown changelog a označování tagy vX.Y.Z

**Comment by VitekJezek** [comment]
hmpf, asi by bylo dobré to spíš psát do samotné appky. Co říkáte do dát do "můj účet"? Tj. jak se tam mění heslo / odhlašuje se, tak prostě pod to dát pár posledních věci, co se kdy změnili... To se může hodit si myslím.

Ideas?

//cc @zbycz

**Comment by zbycz** [comment]
Jsem pro - nějaká stránka "about"...?

**Comment by VitekJezek** [comment]
hodil jsem to nakonec do "můj účet", abych nedělal další stránku. Jak je to dole tak mi to moc nepřekáží. Co myslíte?

**Comment by zbycz** [comment]
za mě ok.
