### ISSUE TITLE
Seká se mapa

### ISSUE THREAD

**Issue by Aidam** [Clevis/ReKola-Public#15]
Mapa při vracení kola raguje na přetahování asi tak s třívteřinovym zpožděním - trefit se přesně do polohy kola tak zabere dost času a trpělivosti. Bohužel, kvuli nefunkční lokalizaci, to musím dělat vždycky při vracení. Chce se mi do toho proto čim dál tim míň.
Používám HTC ONE V s androidem 4.0.3

**Comment by enzy** [comment]
Je mi líto, že máš takový pech na problémy. Na ladění výkonnosti jsme se ještě nedostali (a to mapa používá jen Google API) a i tak budeme mít dost svázané ruce, dokud se nebude dělat aplikace nativní.

ad lokalizace: nefunguje ti vůbec nebo se neaktualizuje?

**Comment by enzy** [comment]
Dej prosím vědět, zdali se to s novou verzí zlepšilo.

**Comment by VitekJezek** [comment]
@Aidam, mám informace, že by to mělo být lepší. Toto issue zavírám; pokud tomu tak není otevři pak prosím nové.
