### ISSUE TITLE
Aplikace přidaná na plochu nefunguje na iOS7

### ISSUE THREAD

**Issue by honzasladek** [Clevis/ReKola-Public#16]
Přidal jsem si ReKola na plochu, v sobotu vše fungovalo bez problémů. Dnes se mi zasekne obrazovka na točítku "Lokalizuji..." a nejde s tím nic dělat. Povolenou lokalizaci pro ReKola v nastavení mám.

Testovací zařízení: iPhone 4, iOS 7.0.2

V prohlížeči po zadání app.rekola.cz to ovšem funguje.

**Comment by enzy** [comment]
Nápady co s tím? Tohle já nedokážu odladit.

**Comment by honzasladek** [comment]
Udělám výhledově research, proč se to děje. Zatím jsem to sem napsal hlavně proto, abychom o tom věděli.

**Comment by enzy** [comment]
@honzasladek Otestuj prosím na nové verzi, díky!

**Comment by VitekJezek** [comment]
@honzasladek, je to tedy OK? Uzavřeš to prosím?

**Comment by honzasladek** [comment]
Fixed.
