### ISSUE TITLE
Kolo 158 (aneb náhodné pujčení kola, které nemá verifikační kód)

### ISSUE THREAD

**Issue by petraneugebauerova** [Clevis/ReKola-Public#19]
Tenhle kousek mi porad appka hlasi, ze je ode me nejdriv 417 m, pak 6 m a ted 13 m, adresa Pražský okruh 104 - at chodim jak chodim, tak kolo tady nenachazim - bud spatne zalogovano anebo blbne mobilni web. Umisteni na mapce navic ukazuje kousek vedle nez je adresa Milady Horákové 104 (Pražský okruh 104) - 104 je v Etnetere.

**Comment by VitekJezek** [comment]
podle logu bylo uvázáno `2013-09-30 12:15:09` od Zbyňka Hraše (toho hádám budeš znát ; ) a to na pozici https://maps.google.com/?q=50.0981%0914.4106. Ještě teda 1. tam nějak čachroval Adam Jaroš ( @Aidam ), ale ten ho hned vrátil na tu samou pozici, tak nevím, zda-li nešlo o jen překlik (Adame?).

Mám Zbyňkovi napsat kam jej vrátil a nebo si to s ním zkusíš vyříkat sama?

(Mohlo být také ukradené).

**Comment by petraneugebauerova** [comment]
30.9. jo? no  vcera tu bylo uvazano - videla jsem ho a dnes uz ne... tak ja zkusim Zbynka dohonit, ale nevim, jestli to bude v jeho rukou, dikes

**Comment by Aidam** [comment]
Nazdarek, cislo 158 mi nic nerika jedno kolo jsem si omylem pujcil a hned vrátil, když jsem omylem potvrdil prázdnej identifikační kód. Ted jsem to zkusil znova a je to nejspíš ono - nevim ale kde stálo/stojí skutecne, tak jsem ho vrátil na mojí aktuální pozici

**Comment by petraneugebauerova** [comment]
hm ted se loglo v ulici U zemepisneho ustavu 1-3, chtelo by to overit, zda tam skutecne je - je to kolo s problemem - spatne fungujici pedal. Jinak kdyz si ho rozkliknu v aplikaci - tak mi nejde najet na  " Problémy" - nedá se sjet dolů - je to kouslé, vidím max button "půjčit kolo", verze android 4.1.2

**Comment by VitekJezek** [comment]
ou, to je bug appky! Vidím to v logu! 

Kolo 158 nemá totiž kód kola a ani kód zámku. Myslím, že stále je v dejvické klubovně. (A tím pádem asi i Zbyňek si půjčil jiné kolo - napíšu mu, zda-li nám do toho nevnese trošku světla). Kdykoliv se odešle kód jako prázdný řetězec, tak se pujči toto kolo.

@VaclavSir - mohli by se takové kola vůbec nezobrazovat a nepůjčovat? Tj. když nemají vyplněný kód kola / zámku, tak jsou neviditelná? (možná udělat jen v rámci [issue, co jsme řešili v rámci private repositáře](https://github.com/Clevis/ReKola/issues/47#issuecomment-25536870) pro ukládání "ukradnutých" / "vyřazených" kol).

Jinak viz také tbl api_request ID řádku `2183`: poslalo se `http://app.rekola.cz/server/api/bikes/lock-code?bikeCode=` a pujčilo se kolo 158.

(kolo vracím polohově do Klubovny a omlouvám se za šumy).

**Comment by VaclavSir** [comment]
Udělám.

**Comment by VitekJezek** [comment]
uděláno, takže tady zavírám.
