### ISSUE TITLE
Problem se odemknutim

### ISSUE THREAD

**Issue by jiristepan** [Clevis/ReKola-Public#2]
Dnes jsem si pujcoval kolo c. 714 na Dejvicke.

Aplikace se po zadani kodu 714123 dvakrat sekla. Obevilo se modalni okno ze nacita kod zamku, tocilo se a nimutu nic. Pomohlo az kilnuti browseru, a znovunacteni.

Zarizeni: Android 4.1. nativni browser, signal v ten okamzik vypadal v pohode. 3G se spoustou catek.

**Comment by VitekJezek** [comment]
@enzy - mohl byses na tohle prosím podívat?

**Comment by VitekJezek** [comment]
@jiristepan - snažili jsme se to zreprodukovat, ale nedaří se nám. Dokonce jsem ani nenašel tenhle záznam v API logu. První kolo (`#714`) jsis pujčil `2013-09-20 11:27:38` a poté jej vrátil `2013-09-20 12:20:16`, což vypadá OK. 

Mohl bys to případně zopakovat?

(jinak je deployovaná nová verze, kde se dají reportovat i problémy)
