### ISSUE TITLE
Problém s aplikací

### ISSUE THREAD

**Issue by jiristepan** [Clevis/ReKola-Public#22]
Deska mezi 11.00 a 12.00 jsem měl s aplikací dosti problémy.
- Odhlásila mne a odmítala přihlásit
- Posléze jsem kliknul na půjčit kolo ještě než se načetli kola a tím jsem ji zasekal. Muzel jsem restartovat
- Pak pro změnu nenašla opakovaně polohu

**Comment by VitekJezek** [comment]
tohle by mělo být vyřešené odebráním toho frameworku od Intelu. Jirko, pokud bys měl s tím dále problémy, otevři prosím nové issue.
