### ISSUE TITLE
Prázdný identifikační kód půjčí kolo 158

### ISSUE THREAD

**Issue by Aidam** [Clevis/ReKola-Public#23]
Když necháte prázdný identifikační kód a potvrdíte puůjčování kola, půjčí se vám kolo 158. Stalo se mi to omylem. "Vrátil" jsem ho na svou aktuální pozici, kde ale je skutečně netušim

**Comment by VitekJezek** [comment]
tohle by mělo být vyřešené (každé kolo má verifikační kód & navíc jej umíme v DB "skrýt")
