### ISSUE TITLE
Tlacitka +- na minimape

### ISSUE THREAD

**Issue by kubahorak** [Clevis/ReKola-Public#25]
Z nejakeho duvodu (spatny prohlizec, Android 2.2.2) mi nefunguje pinch-to-zoom na minimape pri vraceni kola.

Slo na minimapu by pridat tlacitka +-? Vyrazne by mi to ulehcilo praci s aplikaci.

**Comment by VitekJezek** [comment]
@enzy, jak moc je těžké je tam přidat?
