### ISSUE TITLE
Při vracení na mapě chybí šipečka

### ISSUE THREAD

**Issue by zbycz** [Clevis/ReKola-Public#26]
Možná jen není smazaná nějaká keš, ale prohlížeč mi tuhle funkcionalitu nenabízí... Před upgrademe aplikace to fungovalo a možná(?) i chilku po něm.

![screenshot_2013-10-10-19-52-55](https://f.cloud.github.com/assets/385047/1309764/d74f1b22-31e4-11e3-8435-98b8e7bfc6f5.png)

**Comment by enzy** [comment]
S šipkou se dlouho nic nedělo, netuším čím by to mohlo být. (já jí tam mám).

Takže se ti to děje neustále?

**Comment by zbycz** [comment]
vlastně se načítá pod mapou - jako by měla nižší z-index. Asi to bude blbě kešlé, musím někde vygooglit jak od-kešovat

**Comment by VitekJezek** [comment]
@zbycz - je to stále aktuální? Nebo se to podařilo opravit?

**Comment by zbycz** [comment]
Stále to nefunguje, kes v prohlí¾eèi jsem mazal. Nevím moc co s tím.
Dne 25.10.2013 21:54 "Vitek Jezek" notifications@github.com napsal(a):

**Comment by VitekJezek** [comment]
@enzy, pomohl bys zde? (třeba v pátek v kanclu, že by ti to pája ukázal?)

**Comment by enzy** [comment]
@zbycz a co máš za verzi systému?

**Comment by zbycz** [comment]
4.0.4 ICS

Jinak dríve to fungovalo a tez je ta sipecka chvilku videt, nez se nactou dlazdice google-maps... Takze nìjaký z-index...?

![screenshot_2013-10-30-11-08-49](https://f.cloud.github.com/assets/385047/1435985/4f27fc10-414c-11e3-9e7f-6c76a75fe208.png)

**Comment by enzy** [comment]
Bug potvrzen ve verzi 4.0.3 (4.0.4), ve starších (2.3) ani novějších (4.1) se nevyskytuje.

**Comment by enzy** [comment]
Fixnuto, deploy později.

**Comment by zbycz** [comment]
LOVE!
