### ISSUE TITLE
prihlaseni do appky (jmeno == email)

### ISSUE THREAD

**Issue by starenka** [Clevis/ReKola-Public#27]
Neni uplne zrejmy, ze input "jmeno" je ve skutecnosti email (alespon me), teda.

**Comment by washeck** [comment]
Díky, právě jsi mi objasnil, proč se mi nedařilo přihlášení. Toto by chtělo opravdu vyřešit co nejdřív.

**Comment by VitekJezek** [comment]
díky za report; to je fakt naše blbost; omlouvám se! 

Opravil jsem to na "E-mail"; good?

**Comment by starenka** [comment]
supr. dik
