### ISSUE TITLE
reset hesla pro prihlaseni

### ISSUE THREAD

**Issue by starenka** [Clevis/ReKola-Public#28]
nevidim/nemuzu najit

**Comment by VitekJezek** [comment]
zatím tam není; možnost je mi napsat maila a já ti ho pošlu ručně : P

Je to future feature, vidím tam důležitější věci; ale díky za reporting!

**Comment by VitekJezek** [comment]
nakonec jsem to tam hodil, když jsem dělal novou registraci : )
