### ISSUE TITLE
geolokace nefunguje a posleze navzdy hijackne browser confirmama

### ISSUE THREAD

**Issue by starenka** [Clevis/ReKola-Public#29]
Na http://app.rekola.cz/#nearby z nejakyho duvodu nedojde k geolokaci zarizeni (geolokace povolena, browser Opera/9.80 (X11; Linux x86_64; AppleWebKit/535.1) Presto/2.12.388 Version/12.16) a posleze jen padaj confirm dialogy s inputem na zadani adresy. I po zadani ale vyskoci porad dokola a nejde zrusit ani pomoci OK ani pomoci Cancel. Jedina moznost je killnout js na strance.

**Comment by starenka** [comment]
To samy se  v podstate deje ve Firefoxu (Iceweaselu) na desktopu. Tam sice po zadani pozice rucne dialog zmizi, ale pravidelne vyskakuje v nejakym intervalu, coz je k uzoufani otravny. 

V Chrome na Androidu (4.3, chrome posledni) to zase pokud nerequestne desktop version taky nic nelokalizuje a jen toci...

**Comment by vaclavrimal** [comment]
Souhlasím, to vyskakovací okno je dost otravné a úplně to zablokuje aplikaci. Co kdyby se tohle varování vůbec nezobrazovalo? Jen ať se to pomaloučku lokalizuje na pozadí. Vždyť ta lokalizace při půjčování kola vlastně není nutná, když stačí zadat číslo kola. A pokud by byla mapka posouvací (tak, jako ta v detailu konkrétního kola), dost by se vyřešilo.
Dělá mi to v Opeře Mobile na Androidu. V androidím nativním prohlížeči ne.

**Comment by VitekJezek** [comment]
@enzy ? Jak by to šlo? (nevidím úplně do technického backgroundu v Androidu).

// já bych si představoval, že když to uživatel zruší (a/nebo odešle prázdný string) tak ho to lokalizuje jako "Praha". A ať se pak stará sám...

Ideas?

**Comment by VitekJezek** [comment]
Tak jsem si to napsal sám; kdyžtak Matěji na to hoď prosím oko. Clevis/Rekola@3e407b242fad43e2920fe3d08fa7a5b829777ef6

Tedy: vyběhne jednou ten JS popup, když lokalizace failne, tak se to hodí do "Praha, ČR", tedy k míráku (hmm, možná tam spíš dát Staromák? nebo dejvice?). 

Anyway - snad OK, zavírám to tedy. Kdyžtak se ozvěte - ať už tady, nebo otevřením nového issue.

**Comment by starenka** [comment]
Zatim to funguje super. Potrapim to este na desktopu. Dik, kluci!

**Comment by enzy** [comment]
@VitekJezek jsi si ale vědom, že to do logů zanáší nepřesnosti, takže s nimi půjde pak špatně pracovat?

**Comment by starenka** [comment]
Btw, jeste jedna vec, ktera s tim souvisi: nejdriv se me to sahodlouze snazi lokalizovat - bud to udela, nebo me to donuti neco napsat a AZ potom to zjisti, ze nejsem prihlasenej :(

**Comment by enzy** [comment]
Šetří se tím request, kdy se předpokládá, že přihlášený jsi, pokud máš uložený token. Jeho vypršení by mělo být okrajovou záležitostí při používání jednoho zařízení.

**Comment by starenka** [comment]
V tom pripade to bude nefunguje dobre, nebo to expiruje v radu nekolika dni, protoze se mi to stava skoro pokazdy, kdyz tam vlezu (rekneme minimalne jednou za tejden)

**Comment by VitekJezek** [comment]
jo, to vypadá na bug v klientovi na Androidu - viz #37. Prosím řešme to tam ; )
