### ISSUE TITLE
Zobrazeni vlastni polohy nebo mapa kol

### ISSUE THREAD

**Issue by jiristepan** [Clevis/ReKola-Public#3]
Prehled kol jen podle adresy mi moc nesedi. Idealni by byla mapa s moji polohou a polohou kol v okoli.

**Comment by VitekJezek** [comment]
O tomhle jsme hodně přemýšleli a bavili se na začátku s UX a frontendistou.

Pokud tomu dobře rozumím, tak je to problematické vzhledem k technologiím - tím, jak jdeme přes Phoengap (a tedy defacto web view) tak na telefonech nejde úplně snadno (= rychle) pracovat s velkým množstvím POI na mapě. Proto je tam aktuální řešení, kdy se načítají nejbližší kola jen do listu. 

Počítáme s tím, že finálně (tj. pokud projekt pojede, bude zvalidizovaný a budou na to prostředky) bude i nativní appka - a tam už by tohle omezení nemělo být. (Inmite se nabídl, že by ho tohle hodně zajímalo, ale teď to není na pořadu dne).

Issue zavírám, pokud by tě k tomu něco zajímalo, můžu provést prokontaktování mezi tebou a těmi "odpovědnými lidmi", napřímo.
