### ISSUE TITLE
kus strev public? http://app.rekola.cz/server/sign/in

### ISSUE THREAD

**Issue by starenka** [Clevis/ReKola-Public#30]
nevim k cemu je to dobry a sem linej to jit stourat, ale asi by to radsi nemelo bejt public?

**Comment by VitekJezek** [comment]
v zásadě není nic proti ničemu aby to bylo public. Jen se tam teď některým uživatelům zobrazoval link na přegeneraci systémových popisků (také nic proti ničemu; ale mohlo to mást).

Časem tady bude nějaká "administrace" pro uživatele (může se tam přihlásit svým jménem) a třeba si tam změnit heslo (což může teď i v appce). 

Uvidíme; každopádně bych řekl, že to není problém. Nebo v tom vidíš něco jiného?
