### ISSUE TITLE
Problém na Windows Phone

### ISSUE THREAD

**Issue by VitekJezek** [Clevis/ReKola-Public#33]
máme nahlášený problém, že aplikace nefunguje (dobře) na Windows Phone.

@enzy se pokoušel to rozhodit v emulátoru; fyzické zařízení bude mít v ruce ve středu 30. 10. večer a uvidí, co uvidí.

**Comment by VitekJezek** [comment]
@enzy , jak to dopadlo?

**Comment by enzy** [comment]
Získal jsem chybovou hlášku `window.onerror ::"Function expected"`, ale ještě jsem se nedostal k honu na ní.

**Comment by VitekJezek** [comment]
Díky za info! A na kdy to vidíš?

**Comment by enzy** [comment]
Dnes jsem nasadil blind-fix a pak teď večer konečně otestoval na WP8, kdy appka v pohodě běhá.
Pak jsem to otestoval ve verzi 7.5, ve které naopak neběhá, takže víme zas o trochu více.

**Comment by VitekJezek** [comment]
@Pulcik - běhá ti to tedy nyní? : )

**Comment by Pulcik** [comment]
Neběhá... Stále stejný "Rozjíždím aplikaci..."

**Comment by enzy** [comment]
@Pulcik napsal by jsi mi prosím verzi systému? Ovšem pokud máš WP8, tak jsem nahraný :/

**Comment by Pulcik** [comment]
WP 7.8, ale mohu to zkusit i na WP8

**Comment by VitekJezek** [comment]
hele kluci, mohli byste to vyzkoušet prosím na jednotlivých telefonech?

Já si to zkoušel na WP8 a fungovalo mi to: 
![img_9327](https://f.cloud.github.com/assets/297491/1648980/1dd08752-59d6-11e3-9bb2-d2faf17da602.jpeg)

**Comment by Pulcik** [comment]
Je tomu tak. Zrovna jsem to sem chtěl napsat.
Měl jsem oba přístroje (WP7.8 i WP8) vedle sebe. Na WP8 app běží. Což je dobrá zpráva. Na starších WP 7.8 ale app neběží. Což je špatná zpráva, ale WP 7.8 je zajisté na ústupu tak to není tak hrozný. Blbý je že já mám staré WP7.8. Avšak to už je můj problém.

**Comment by bouchja1** [comment]
Ahoj, právě jsem to vyzkoušel na Lumia 820 (WP8). Prvně mi to nejelo (UC browser v3.2), ale pak mě napadlo nainstalovat prohlížeč Internet Explorer a zkusit to v něm a podařilo se mi dostat se do aplikace. Takže jede na WP8 v IE, UC browser (http://www.windowsphone.com/cs-cz/store/app/uc-browser/6cda5651-56b9-48b0-8771-91dbc188f873) v3.2 nejede - třeba je to ale verzí nebo typem telefonu, zkusím ohledně toho zjistit víc.

**Comment by VitekJezek** [comment]
kluci,
uzavírám to tedy resultem, že na IEčku s WP8 to jede a ostatním doporučíme upgrade sem. Pokud byste byli proti, pište do komentářů O: )
