### ISSUE TITLE
Na Androidu se stále odhlašuje

### ISSUE THREAD

**Issue by VitekJezek** [Clevis/ReKola-Public#37]
@enzy,
měl jsem tu zrovna Filipa s Androidem (2.3.6, brwoser nativní, hlavičky níže), který mě ukázal moc pěkný bug: kdykoliv kdy aplikaci refreshne, chce po něm login. Myslím, že je to bug na Clientovi, protože server mu vrátí v pořádku data:

```
host: app.rekola.cz
connection: keep-alive
accept-encoding: gzip
accept-language: cs-CZ, en-US
x-wap-profile: http://wap.samsungmobile.com/uaprof/GT-S5660.xml
x-api-key: 1887mkn4xhlbgyjuiab0caz9ymwhpu2gsc9np5rk
cookie: _ga=GA1.2.253605050.1380973919
x-requested-with: XMLHttpRequest
accept-charset: utf-8, iso-8859-1, utf-16, *;q=0.7
referer: http://app.rekola.cz/
user-agent: Mozilla/5.0 (Linux; U; Android 2.3.6; cs-cz; GT-S5660 Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
accept: text/xml, text/html, application/xhtml+xml, image/png, text/plain, */*;q=0.8
content-type: application/json
cache-control: no-cache
pragma: no-cache
```

Jinak to samé asi [reportoval stařenka vedle](https://github.com/Clevis/ReKola-Public/issues/29#issuecomment-27639304).

Mohl byses na to prosím mrknout?

**Comment by starenka** [comment]
me to neodhlasuje porad, ale na muj vkus dost casto. coz by asi nebylo tak votravny, kdyby to predtim pul hodiny nelokalizovalo a pak nezjistilo, ze nejsem prihlasenej (coz uz jsem psal v tom issue).

**Comment by Piskvor** [comment]
Stock browser na Androidu 4.0.4 taky zrejme drzi login jenom per-session - pri otevreni o par desitek minut pozdeji chce znova jmeno a heslo. (Myslel jsem, ze je to featura ;))

**Comment by filip-jezek** [comment]
@enzy Testováno naposled včera a problém přetrvává - je to fakt vopich pokaždý co zapnu app se zas přihlašovat, když to ani neni vyplněný z minula. Mohlo by se to prosím nějak pohnout? Klidně se stavím s android 2.6.1 jestli to něčemu pomůže.

Dík F/

**Comment by enzy** [comment]
@filip-jezek práce se na appce nepohli žádným směrem, @VitekJezek mi musí vyjednat závazek na projekt
