### ISSUE TITLE
KML není validní, obsahuje HTML tag(y)

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#54]
KML z http://app.rekola.cz/server/kml si GMaps přechroupá po svém, ale nenačítá se to v některých aplikacích, které KML jinak podporují (např. Locus pro Android). 

Problém dělá ten BR tag, který je uvnitř DESCRIPTION . Prozatím jsem si to pro ten Locus sbastlil a sflikoval skriptem, který si jednou za hodinu stáhne KML, vymění brejky za \n, a publikuje to na http://i.piskvor.org/rekola/fixed.kml ; doufám, že takové minimální scrapování nevadí.

Mohl bych (někdy, výhledově, do budoucna) požádat o KML feed, z něhož budou vyházeny HTML tagy?

**Comment by zbycz** [comment]
Taky jsem si toho všiml, beru si to na sebe, rád to opravím. Jen nevím kdy :-)
