### ISSUE TITLE
Při půjčení/vrácení kola automaticky smazat flag "Kolo tu není"

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#56]
Před pár dny jsem nenašel kolo, i označil jsem ho jako "kolo tu není"; dnes ráno se pohnulo jinam, čili ho evidentně našel někdo jiný (někde tam asi přece jenom bylo). Zůstal mu ale příznak "nepojízdné" kvůli mému hlášení, smazal jsem ho ručně.

Napadlo mě tedy, že má-li kolo stav "není tu", a přesto si ho někdo vypůjčí, jde evidentně o false positive stav, který by se měl výpůjčkou automaticky vymazat.

V obecnější rovině možná u "nepojízdného" kola zobrazit při půjčení/vrácení nějaké upozornění "když na tom evidentně jedeš, můžeš zkontrolovat, jestli to hlášení o nepojízdnosti nekecá?" - což už zdaleka není automatický, a nejsem si jist, zda by to nebylo matoucí pro uživatele.

**Comment by vladimirkroupa** [comment]
To me dnes taky napadlo, to by se hodilo.

**Comment by Piskvor** [comment]
Aha, tak jsem úplně náhodou v praxi zjistil, že už to je hotový. Díky!
