### ISSUE TITLE
Lepší generátor auth hashe pro admin KML

### ISSUE THREAD

**Issue by VitekJezek** [Clevis/ReKola-Public#59]
- zatím je to přes hardcoded hash (ale nejde o žádné "tajné" data)
- chtělo by to přes uživatele, dát mu jednorázový hash (zjistit, zda-li to vůbec půjde, aneb odkud se táhá session když google mapa si tahá kml? serverside vs. cliendside)

**Comment by zbycz** [comment]
KML se tahá prohlížečem přes AJAX (čili to funguje jen v rámci domény) a tedy by stačila asi session. Ale přímo gmaps jsem nezkoušel, mám to otestované na několika jiných.

**Comment by VitekJezek** [comment]
žádný admin KML asi zatím netřeba, takže netřeba ni tohle
