### ISSUE TITLE
export KML (i pro Prahou na kole)

### ISSUE THREAD

**Issue by banterCZ** [Clevis/ReKola-Public#6]
export KML souborů, aby šlo dobře zobrazit na mapě Prahou na kole; či jinde ve widgetech.

---

dříve (před 2.10.2013) : **mít na mapě nejbližší stojany**, což je nyní #18
- třeba z http://mapa.prahounakole.cz/
- ideálně i s fotkou
- (a možná i jiná "bezpečná místa")

původně (před 24.9.2013): **Pokud existují pevná stanoviště, co k nim přidat i fotku místa?**

**Comment by VitekJezek** [comment]
spíš by to vůbec ty stojany chtělo v první řadě propagovat na té mapě. Uvidíme, jak moc je to prioritní při používání. (zneužil jsem ti tohle issue a doeditoval to k tomu ; )

**Comment by washeck** [comment]
Stojany z PNK můžete načíst z http://mapa.prahounakole.cz/kml/s/ (pokud byste to nenačítali online, ale dělali si vlastní kopii, napište nám, bylo by třeba dořešit aktualizaci - data se mění dost často)

Naopak, pokud jste schopni zpřístupnit aktualní polohy vašich kol v KML (nebo jiném formátu podporovaném OpenLayers), rádi přidáme jako vrsvtu v mapě PNK.

**Comment by VaclavSir** [comment]
Tak máme KML: http://app.rekola.cz/server/api/bikes/kml

**Comment by VitekJezek** [comment]
@washeck - geniální! Moc rád bych to s tebou ještě nějak doprobral a dofinalizoval. Bylo by možný se semnou nějak spojit? (myslel jsem, že jsi Vašek Kříž, ale to evidentně nejsi O: )

tel: 776 184 835
skype: vitek.jezek
FB: www.fb.com/jezek.vitek
mail: me@vitekjezek.com
