### ISSUE TITLE
Popis umístění kola nesouhlasí s umístěním šipky - now what?

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#61]
Tento problém potkávám neustále na náměstí Míru (s různými koly, ale předpokládám, že s týmž uživatelem (?)): původně jsem myslel, že je to #53, ale vizte predvčerejší screenhot: popis naprosto nesouhlasí s lokací - a pak se v mapě ukazuje kolo někde, kde v reálu vůbec není, což blbne nejenom mapu, ale i "nejbližší kola" :( 

Popis "pred Pfuk" indikuje, že by mělo být před právnickou fakultou na Starém městě, ale podle šipky je na Míráku ve dvoře.

![2013-12-11 17 16 08](https://f.cloud.github.com/assets/917239/1742651/a9211a14-63ff-11e3-9a89-09186a43b530.png)

**Comment by VitekJezek** [comment]
tohle je problém, že Michal Němeček to špatně vrátil. Veřejně mu tímto vyhobujeme, a píšu si do velkého backlogu k nabodování řešení tohoto (asi nahlášení, že kolo je jinde a to bude nějak persekuovat člověka).

**Comment by washeck** [comment]
Btw, na Nám. Míru se to stává často proto, že při selhání lokalizace se toto místo zvolí jako náhradní. Pokud děláte data mining, kde uživatelé nejčastěji pouštějí app, předpokládám, že mírák tam bude taky dost výrazně vidět.
