### ISSUE TITLE
Rozbitá URL po redesignu webu

### ISSUE THREAD

**Issue by washeck** [Clevis/ReKola-Public#65]
Spuštěním webu pro ostrý provoz přestaly fungovat stávající odkazy. Z těch co mě zajímají zejména mapa (http://www.rekola.cz/map) a KML export používaný v Locusu nebo Prahou na kole (http://app.rekola.cz/server/api/bikes/kml)

**Comment by enzy** [comment]
Fw @tsusanka

**Comment by tsusanka** [comment]
Ad KML export: adresa se změnila na http://rekola.cz/api/bikes/kml 
Ad mapa musí odpovědět @VitekJezek , nevím o co se jedná

**Comment by Piskvor** [comment]
Aha, vyborne, diky; dam vedet PnK, uz se taky podivovali ohledne
nefunkcniho exportu.
Dne 22.3.2014 18:30 "Tomas Susanka" notifications@github.com napsal(a):

**Comment by zbycz** [comment]
vyřešené PKN - díky! 
 též funguje rekola.cz/map
