### ISSUE TITLE
V appce nefunguje reset hesla

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#66]
http://www.rekola.cz/login/password-recovery :

Page Not Found

The page you requested could not be found. It is possible that the address is incorrect, or that the page no longer exists. Please use a search engine to find what you are looking for.

error 404

**Comment by VitekJezek** [comment]
už by to mělo ject, že? ; )

**Comment by Piskvor** [comment]
Ahoj, pro vhodně zvolený obor "ject" ;) - resetovací maily chodí, ale po odeslání formuláře nevidím feedback, že se  něco stalo, takže jsem si ten mail poslal celkem třikrát. Šlo by tam hodit "odeslali jsme mail na blabla@example.com"?
