### ISSUE TITLE
kola ve feedu vs. v appce

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#67]
http://www.rekola.cz/api/bikes/kml obsahuje kola, na https://moje.rekola.cz/#nearby se mi nezobrazuje ani jedno.

**Comment by Piskvor** [comment]
Zajímavé. Na androidím prohlížeči mi appka funguje, v desktopovém Chrome 34.0.1847.116 na Linuxu nevidím kola okolo: request na https://moje.rekola.cz/api/bikes?lat=50.0853839811726&lng=14.417495727539062 vrací response o délce 0

**Comment by Piskvor** [comment]
Firefox taky ne:

ReferenceError: google is not defined

...ReportView=BasePanelView.extend({id:"bikeReport",template:_.template($("#templat...

rekola.js (řádek 3)

**Comment by zbycz** [comment]
Problém je v https:// verzi, v současné chvíli nám zlobí a pracujeme na
opravě. http://moje.rekola.cz funguje správně.

**Comment by Piskvor** [comment]
Aha - lezl jsem tam přes app.rekola.cz a nenapadlo mě zkusit to bez HTTPS.
