### ISSUE TITLE
nepojmenovaná kola ve feedu - enhancement

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#69]
Bylo by možné u nepojmenovaných kol ve feedu zobrazovat identifikační číslo? Locus bere tag Placemark>name jako unikátní identifikátor (což je naivní, jistě, ale nic lepšího tam není), a zdráhá se naimportovat deset bodů se stejným názvem:
Šlo by aspoň udělat to, co mají pojmenovaná kola?

```
<name>Kostroma [#94] [vráceno 16. 04.]</name>
```

Čili pokud kolo nemá název, zobrazit

```
 <name>[#314] [vráceno 16. 04.]</name>
```

?

**Comment by zbycz** [comment]
Tohle vzniklo rychlým přidáváním kol v posledních dnech, obecně se to stávat nebude. Nyní již to funguje.
