### ISSUE TITLE
Samovracení kol

### ISSUE THREAD

**Issue by Aidam** [Clevis/ReKola-Public#7]
Dvakrát se mi stalo (naposledy v pondělí ráno), že jsem si pujčil kolo a když jsem ho po jízdě chtěl vrátit, zobrazovaly se mi nejbližší kola - jako bych ho neměl pujčené - musel jsem ho pro aktualizování pozice znova pujčit a vrátit. 
Android 403 na HTC one

**Comment by VitekJezek** [comment]
@VaclavSir , dle logu je tomu opravdu tak. Např. id logu `780` řiká `LockCode:get` v `2013-09-23 07:31:22` a vrátí to správný JSON. Následně je autorizace  (`781`) a pak opět `LockCode:get` v `2013-09-23 07:40:19` vrátí správný JSON. To by imho nemělo nastat, ne? 

Alespoň na backendu by ten druhý neměl projít, protože by kolo už mělo být půjčené (?). A kdyby ten první neprošel vzhledem k zabezpečení, tak by se něměl vrátit ten validní JSON, pletu se?

//cc @Mockova

**Comment by enzy** [comment]
Asi bude platit stejný komentář jako zde: https://github.com/Clevis/ReKola-Public/issues/8#issuecomment-25038885

@VitekJezek mohl bys to pro jistotu zkontrolovat v logu?

**Comment by VitekJezek** [comment]
já bych řekl, že tady jde (i?) o backend problém, který jsme neaktualizovali (on půjčil 2x to kolo!). Počkáme na vyjádření @VaclavSir .

**Comment by VaclavSir** [comment]
Pravdu má @enzy , byla to ta chyba frontendu, že po přihlášení se aplikace neptala serveru na půjčené kolo. Je to opravené od pondělí večer (19:09).

Ono to v logu API vypadá, jako že dvakrát půjčil kolo, ale to proto, že pokud voláš /bikes/{id}/lock-code na kole, které už máš půjčené, tak ti to ty informace o kole vrátí (viz [test case](https://github.com/Clevis/ReKola/blob/master/tests/cases/Integration/Api/Bikes/LockCode_get_Test.php#L40)). Je to dobře vidět v logu akcí, kde se zaznamená jenom to první volání.
