### ISSUE TITLE
Použitelnost dámských kol

### ISSUE THREAD

**Issue by jesuspraha** [Clevis/ReKola-Public#74]
Mám možná stupidní dotaz, ale zeptat se musím. Měřím skoro 190cm a vážím cca 100kg. Dnes jsem si chtěl na Tyláku půjčit kolo, ale zalekl jsem se, když jsem ho viděl.
Můžu si při mé velikosti půjčovat i dámská kola? Zvládnou to?
Dík 
Petr

**Comment by zbycz** [comment]
Díky za reálné zvážení možného problému. Rám je určitě v pohodě, staré ocelové kolo je prostě pevné. Spíše co může trpět jsou pneumatiky, zkontroluj tedy (třeba nasednutím na zamčené kolo), jestli nejsou úplně rozpláclé. 
No a když bude problém, tak ho nahlaš přes aplikaci.
