### ISSUE TITLE
Idea: podrobnější informace o umístění kola ve feedu

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#76]
http://moje.rekola.cz/api/bikes/kml - a z něj i http://rekola.cz/map a všechny ostatní aplikace - ukazuje všechna kola ve všech městech; jakkoli to je odhadnutelné filtrováním dle lokace (čili [16.6160014393,49.204313591] asi nepřijelo z Prahy), šlo by ve feedu nějak označit, ve kterém městě to kolo je? 

A když už jsme u toho, mohla by ve feedu být i adresa? Z geolokace by být dostupná měla...(ale to už je jen takový nápad)

```
<Placemark>
    <name>Veles [#7] [vráceno 17. 04.]</name>
    <description>
        <![CDATA[
        Kolo s blatníky, nosičem a protišlapnou brzdou<br /> Naproti Sakure u skoly
        ]]>
    </description>
    <Point>
        <coordinates>14.3995255977,50.1006937035</coordinates>
        <city><![CDATA[Praha]]></city>
        <address><![CDATA[Kolovratská 8, Praha-Praha 10, Česká republika]]></address>
    </Point>
    <styleUrl>#rekolaBroken</styleUrl>
</Placemark>
```

**Comment by Mosquit** [comment]
Adresu (a tedy i město) lze zjistit ze souřadnic například pomocí Google Geocoding API.
https://developers.google.com/maps/documentation/geocoding/#JSON 
a je to vcelku rychlé. 

Navíc mám pocit, že KML Point nemůže obsahovat element city, ale vyzkoušené to nemám. Asi by to ale mohlo být někde u Placemarku.

**Comment by Piskvor** [comment]
Geocoding API mame i vlastni, nemluvě o oblíbené větičce "The Geocoding API may only be used in conjunction with a Google map; geocoding results without displaying them on a map is prohibited" na té stránce, na kterou odkazuješ. Spíš jsem si říkal, že ta data už někde máme, takže mi připadá snazší je prostě vypsat, než je krkolomně zase dopočítávat.

**Comment by Piskvor** [comment]
Netrvám na tom, že by to mělo být v tom Pointu, to byl příklad, jak si to zhruba představuju :)

**Comment by zbycz** [comment]
Rozšíření KML není problém - nebudou mít některé prohlížeče problém s nestandardními tagy? 
Můžeš to prosím ověřit na google maps a Locus?

**Comment by Piskvor** [comment]
Dne 28.4.2014 11:58, Pavel Zbytovský napsal(a):

**Comment by Piskvor** [comment]
No, jednak by se teda hodilo IDčko u Placemarku ( validátor držkuje: http://feedvalidator.org/docs/warning/MissingId.html ) - předpokládám, že ID kola je jednoznačné?

```
<Placemark id="777"><name>Král Přemysl [#777] [vráceno 26. 04.]</name>
<description><!    [CDATA[Kolo s přehazovačkou (2x6 rychlostí) a blatníky<br />

Před Výstavištěm směrem k Planetariu]]></description>
<Point><coordinates>14.4315270114,50.1044297691</coordinates></Point>
<styleUrl>#rekolaBug</styleUrl>
</Placemark>
```

a potom, specifikace umožňuje `ExtendedData` - https://developers.google.com/kml/documentation/extendeddata

```
    <Placemark id="777">
        <name>Král Přemysl [#777] [vráceno 26. 04.]</name>
        <ExtendedData>
            <Data name="address">
                <value><![CDATA[ U Výstaviště, Bubeneč, Praha, Hlavní město Praha, Praha, 17000, Česko]]></value>
            </Data>
            <Data name="city">
                <value><![CDATA[Praha]]></value>
            </Data>
            <Data name="issues">
                <value><![CDATA[Fskutčnosti vzducholoď]]></value>
            </Data>
        </ExtendedData>
        <description><![CDATA[Kolo s přehazovačkou (2x6 rychlostí) a blatníky<br />

Před Výstavištěm směrem k Planetariu]]></description>
        <Point>
            <coordinates>14.4315270114,50.1044297691</coordinates>
        </Point>
        <styleUrl>#rekolaBug</styleUrl>
    </Placemark>
```

Ta "city" tam technicky vzato bejt nemusí, ale medle by mohla označovat původ kola, ne jeho umístění: když bude kolo v Úněticích, tak jen podle adresy Prahu nepoznám ;) No a teda hlavně by mohla umožňovat filtrování jinak, než podle geokoordinátů.

V Google Maps, Google Earth i v Locusu to funguje; LeafletJS s tím taky nemá problém.

Viz:
http://i.piskvor.org/rekola/test3.kml
https://maps.google.com/?q=http://i.piskvor.org/rekola/test3.kml
http://i.piskvor.org/rekola/leaflet-example/

**Comment by zbycz** [comment]
Extended info jsem do feedu přidal, ale berte to zatím experimentální. Zobrazují se ty data v Locusu? Na gmaps vidět pochopitelně nejsou.

http://moje.rekola.cz/api/bikes/kml

**Comment by Piskvor** [comment]
Z feedu to leze ve správném formátu, díky; leč Locus to parsuje nějak blbě. (To ale není problém ReKol, že ;))

**Comment by Piskvor** [comment]
Ha, a s verzí 3.0.0 už to Locus zobrazuje dobře - viz screenshot
![2014-05-30 10 29 47](https://cloud.githubusercontent.com/assets/917239/3128519/3795621a-e7d5-11e3-8162-0326cbab45fa.png)
