### ISSUE TITLE
Nekonzistentne pomenovanie kol vo feede

### ISSUE THREAD

**Issue by mnicky** [Clevis/ReKola-Public#77]
Kola vo feede (http://moje.rekola.cz/api/bikes/kml) nie su konzistentne pomenovane:
- Niektore kola nemaju cislo: Aloisie, hluchoň, Kajetán, Král Přemysl, Markét, Marquez, Noční pták, Ošklivec Bivoj, ralfík, Slunečník, Tereza Koloběžka, Trockij, Uni...
- Niektore zasa nemaju meno: #173
- A minimalne dve kola nemaju ani cislo ani meno :(

**Comment by enzy** [comment]
V poli jméno má být pouze jméno, ne další údaje.

Toto nekonzistentní chování je dočasné ohnutí dat v DB od @VitekJezek, který to také v brzké době napraví, že?

**Comment by Piskvor** [comment]
Pokud už se bude hýbat s formátem dat ve feedu, dovolím si tu přihřát svou polívčičku s  #76  ;)

**Comment by zbycz** [comment]
Kola jsem pojmenoval konzistentně - ale může to do budoucna zase někdo změnit. Jsou tam tři nepojmenované, tak mají aspoň v názvu ID.
