### ISSUE TITLE
Admin přidávání uživatelů

### ISSUE THREAD

**Issue by filip-jezek** [Clevis/ReKola-Public#78]
v admin rozhraní padá přidávání uživatelů s error 500 (i s čistou cache).
.

**Comment by filip-jezek** [comment]
stále padá předregistrace.

Bylo by dobré rozšířit i na editaci uživatelů - edit telefon, adresu a dobu platnosti. Jen pro userlevel admin (nebo nový?), jde o citlivá data.

**Comment by zbycz** [comment]
Měla by fungovat ta "registrace" - ta stará předregistrace asi bude zabugovaná. Pokusím se na to podívat, ale máme toho na práci dost.

**Comment by VitekJezek** [comment]
předregistraci jsem úplně vyhodil / skryl z administrace. Přidáme jí až v rámci nového RFC (pojďme se o tom bavit na BCX); stejně jako další funkcionality.
