### ISSUE TITLE
Stanovy -> error 404

### ISSUE THREAD

**Issue by mnicky** [Clevis/ReKola-Public#79]
Stranka http://www.rekola.cz/pages/stanovy neexistuje, hadze error 404.

**Comment by mnicky** [comment]
Doplnim ze je na nu link zo stranky http://www.rekola.cz/podminky, ktory by asi mal byt opraveny na http://www.rekola.cz/pages/rules :)

**Comment by zbycz** [comment]
dík! opraveno
