### ISSUE TITLE
Dialog vrátit kolo se zobrazuje i po vrácení

### ISSUE THREAD

**Issue by Aidam** [Clevis/ReKola-Public#8]
Už dvakrát se mi stalo, že po vrácení kola se znova objevil dialog vrátit kolo. Pokud jsem ho potvrdil, vypadla chybová hláška kolo nemáte pujčené. 

Nativní browser na Android 403 na HTC one V

**Comment by enzy** [comment]
Toto řešila poslední aktualizace, která by už měla být online. Pokud problém stále přetrvává, zkus smazat cache prohlížeče.

**Comment by VaclavSir** [comment]
Já to říkal už dávno, že musíme nasadit grunt-hashres. Radit koncovým uživatelům, aby mazali cache prohlížeče...
