### ISSUE TITLE
Poloha kola Stribog - Ostrava?

### ISSUE THREAD

**Issue by mnicky** [Clevis/ReKola-Public#80]
Ktovie preco, kolo Stribog sa podla mapky https://maps.google.com/?q=http://moje.rekola.cz/api/bikes/kml nachadza v Ostrave :)

Zadana adresa by aj sedela (Sokolovska 69), akurat mesto je ine... Napada ma, ci nejde o chybu priradenia suradnic k polohe zadanej sms-kou...

Inak uz vcera som si vsimol, ze Stribog mal podla mapky byt na Karlaku, ale v skutocnosti sa tam nenachadzal (minimalne som si ho tam nevsimol, ked som nahodou siel okolo). Podla popisu v texte bol vrateny na Senovaznej 3...

**Comment by Piskvor** [comment]
Whoa! No, to by odpovidalo - geolokace vraci prvni Ovu; zkusim to nejak zabiasovat podle mesta...

**Comment by Piskvor** [comment]
No, to je v zasade taky moznost, ale je-li uzivatel v 9:30 v Praze na
Florenci, nic nam to nerika o tom, kde bude ve 13:00. Naproti tomu kola
jsou predvidatelnejsi - pokud je to brnenske kolo, je v lidskych moznostech
ho tyz den vratit v Olomouci, ale je to hodne nepravdepodobne.
Dne 30.4.2014 16:37 "Marek Šrank" notifications@github.com napsal(a):

**Comment by Piskvor** [comment]
Jinymi slovy, problem s SMS geolokaci je hlavne pri vraceni, a vime, odkud je pujceny kolo - takze muzeme vyuzit tuto informaci; mam uz v tomto smeru neco rozdelany.

**Comment by Piskvor** [comment]
Jo, to je přesně to, o čem jsem psal prve: "bias podle města."

**Comment by mnicky** [comment]
Zda sa ze 'Slunečník' ma aktualne rovnaky problem. Momentalne ho zobrazuje na Evropske ulici v Pribrami :)

``` xml
<Placemark id="997">
<name>Slunečník [#997] [vráceno 06. 05.]</name>
<description>
<![CDATA[Dámské kolo s blatníky, nosičem a protišlapnou brzdou<br /> u hotelu diplomat ]]>
</description>
<Point><coordinates>14.0204775,49.6982159</coordinates></Point>
<ExtendedData>
<Data name="issues"><value>JIný problém</value></Data>
<Data name="city"><value>praha</value></Data>
<Data name="address"><value>Evropská </value></Data>
</ExtendedData>
<styleUrl>#rekolaBug</styleUrl>
</Placemark>

```

**Comment by Piskvor** [comment]
Mimochodem, tohle taky musíme řešit. "Umístění - Evropská, Praha; hledej šmudlo" - máme log úspěšných/neúspěšných geolokací, @tsusanka ?

**Comment by tsusanka** [comment]
můžeš na to mrknout @zbycz ?

**Comment by mnicky** [comment]
Rovnaky problem, kolo Volavka sa tvari ze je v Ostrave :)

**Comment by mnicky** [comment]
Len pre info: La petite je momentalne v Novem meste nad Metuji :)

**Comment by zbycz** [comment]
Vracení přes SMSky by mělo být nyní fixlé. Kdyby to zlobilo, znovu případně otevřete.

**Comment by Piskvor** [comment]
Close, but no cigar. A tohle určitě není geolokací, páč ta by měla mít nahraná data jen za ČR, a tady je to uprostřed řeky:
![wheeee](https://cloud.githubusercontent.com/assets/917239/3091223/c6918e6e-e599-11e3-8b86-13640039781f.png)

**Comment by zbycz** [comment]
Přesně tak - tohle vyloženě vrátil konkrétní uživatel na tohle místo (buď chybná lokace nebo mock) a v té aplikaci nelze snadno odscrollovat jinam, tak to nechal tady a napsal polohu do poznámky. Opraveno.

Kdyžtak pls na chybně lokovaná kola, dávejte klidně nová issue.

**Comment by Piskvor** [comment]
mock nebo nepřesná lokace by mohla souviset s #83 - geolokace podle IP adresy+proxy může upíchnout kamkoli (já jsem třeba furt na jihu Čech ;)), ale vrací velmi nízkou přesnost.
