### ISSUE TITLE
Počet nalezených kol

### ISSUE THREAD

**Issue by rolfovo** [Clevis/ReKola-Public#82]
Počet kol vracených aploikací i z webu je 20 a k dalším se nedá dostat. Protože se nedá poloha nastavit ručně, bylo by dobré neomezovat vrácená kola na 20, nebo alespoň přidat možnost "dalších 20" nebo něco podobného

**Comment by VitekJezek** [comment]
díky za report; dovolím si to ale rovnou uzavřít. Je to pořešené v nativní app (již brzy u vašich knihkupců [a marketů]!) a pak by to chtělo nějak lépe udělat i ve web app (pokud s tím budeme nějak rozumně chtít pokračovat ...).
