### ISSUE TITLE
Zóna Praha-Hrad nesmyslně míchá dvě oblasti

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#84]
Podle tohoto https://mapsengine.google.com/map/viewer?mid=zgeJLInzXId4.k1PsMudMM5w4 je mezi Letnou, Dejvicema a Smíchovem zóna Hrad, s poznámkou, že nebude spuštěna.

Problém je v tom, že směšuje Hradčany (na kopci nad Dejvicema) s Malou Stranou (u Vltavy, mezi Smíchovem a Letnou), dvě oblasti oddělené desítkami výškových metrů. Na Hradčany jezdí málokdo, do/přes MS furt někdo (otevřu mapu právě teď, vidím tu čtyři různá kola, a to jsem dneska ani jedno z nich nespáchal). Nedávalo by větší smysl tuhle zónu zúžit na tu východní  třetinu - totiž na Malou Stranu, než tvrdit, že _hic sunt leones_?

**Comment by mnicky** [comment]
Myslim si ze otvarat/zatvarat/upravovat zony podla celkovej statistiky ich pouzivanosti (nieco ako http://rekola.cz/register/it-works) je vzdy rozumne riesenie...

**Comment by Piskvor** [comment]
To je v podstate to, co jsem se snazil rict :)
Dne 8.5.2014 12:57 "Marek Šrank" notifications@github.com napsal(a):
