### ISSUE TITLE
bug: Vráceni pres SMS smaže issues?

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#85]
Včera jsem si půjčil kolo Dolfík, který mělo nějaký issues; dojel jsem na něm, vrátil ho přes SMS - a ejhle, issues zmizely. (Přitom technicky by vracení po SMS mělo využívat API úplně stejně, jako vracení z appky...?)

**Comment by zbycz** [comment]
Možná je mezitím admin odmazal? Technicky se to dít nemůže, jedině se po půjčení kola mažou issuečka "Kolo tu není".

Kdyby se opakovalo, prosím, reportuj.

**Comment by Piskvor** [comment]
To je možný - sleduju to ostřížím zrakem, a zatím jsem si dalšího případu nevšiml.
