### ISSUE TITLE
fr: vizuálně odlišit ikonky "bug" a "broken"

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#86]
Ikonky rekolaBug a rekolaBroken jsou vizuálně hodně podobný, byť významově jsou dost daleko; možná by stálo za to je nějak odlišit (Xko udělat červený?)

**Comment by zbycz** [comment]
Co si myslíš o nápadu "rozbitá kola vůbec neukazovat" - jeden uživatel mi říkal, že to je dost frustrující vidět rozbité kola okolo.

**Comment by Piskvor** [comment]
Jestli je to otázka na mě, musím říct "nevím" - některá rozbitá kola jsou opravitelná kolemjdoucími (ohnutý blatník, některé blbě zamčené zámky), některá ne (píchlá duše, nebrzdící brzdy).

S tou frustrací ale souhlasím - jednu dobu jsem ve svých oblastech pohybu viděl na mapě jen hromadu nefunkčních kol; v takovém případě by snad bylo lepší nevidět je.

**Comment by zbycz** [comment]
nevyjádřil jsem se přesně - nezobrazovat jen přímo nepojizdná (rekolaBroken). Proberu to ještě někde..

**Comment by Glutexo** [comment]
Tak frustrující – ono hlavně pokud nehledáš přímo ta rozbitá kvůli opravě, tak jsou ti na mapě beztak k ničemu…
