### ISSUE TITLE
Nahlášení problému kola

### ISSUE THREAD

**Issue by tomkukral** [Clevis/ReKola-Public#87]
U kola, které má nahlášený nějaký problém by mělo být možné nahlásit další až po zobrazení seznamu problémů.

Nahlásil jsem chybějící matku u přední osy kola "Noční pták", mezitím s ním lidé vesele jezdili a někdo dokonce po dvou dnech nahlásil úplně shodný problém. Z toho je jasné, že to ten člověk vůbec nečetl a celkově lidi nějaké problémy kola vůbec neřeší a jezdí dokud tomu neupadnou obě kola.

**Comment by Piskvor** [comment]
+1. Možná by pomohlo zobrazovat problémy už v detailu kola?

**Comment by tomkukral** [comment]
Nebo tlačítko "Nahlásit problém" přesunout do view issues

**Comment by anitramt** [comment]
V nové aplikaci (která je jinak super!) je to, že je na kole nějaký problém špatně čitelné, doporučovala bych to dát s nějakým zvýrazněním..jak je to v mapce před aplikací..

**Comment by tomkukral** [comment]
Closing as stale
