### ISSUE TITLE
Gamifikace

### ISSUE THREAD

**Issue by tomkukral** [Clevis/ReKola-Public#88]
Líbilo by se mi, kdybych ve svém profilu viděl nějakou statistiku, např. ujetou vzdálenost (součet rozdílu mezi místy půjčení a vráceni) nebo počet vypůjčených kol či kola, na kterých jsem ještě nejel.

**Comment by zbycz** [comment]
Data za celou historii provozu máme, ale naprogramování zobrazení statistik je cca do září.
