### ISSUE TITLE
Zatoulana kola (Volavka v Opave a  La petite v Novem meste nad Metuji)

### ISSUE THREAD

**Issue by r0bin-zz** [Clevis/ReKola-Public#89]
Na mape https://maps.google.com/?q=http://moje.rekola.cz/api/bikes/kml jsem objevil dve zatoulana kola. a la issue #80 (Volavka v Opave a La petite v Novem meste nad Metuji). Kdo muzete vratte je na misto. Volavku mam kousek od prace, tak to pripadne zaridim behem obeda (ta je navic zaparkovna chybne u dopravni znacky). Urcite by to slo presunout  administrativne v systemu, tak jestli nekdo muzete, obe kola patri do Prahy. Volavka zjevne do Karlina, vcera jsem ji tam i videl. La petite zrejme na nam. Republiky.

**Comment by Piskvor** [comment]
Jo, to je problem se SMS vracenim, resim to v #80 . Pokud bys Volavku preparkoval, bylo by to super.

**Comment by r0bin-zz** [comment]
Tak kola jsem fyzicky vypujcil a vratil. Pri vraceni jsem mel celkem problemy. Tak jsem to nakonec vracel az z prece od kompu. Kazdopadne, na mape vidim sipku na spravnem miste, kolo vratim a kolo nikde. Otevru pripadne v jinem issue

**Comment by Piskvor** [comment]
Další zatoulané kolo: "Víla Amálka [vráceno 17. 06.]
Dámské kolo s přehazovačkou (1x4 rychlosti) a blatníky
Cihelna 1;nejde odemknout" - až poté, co jsem ho nenašel v pražské Cihelné 1, jsem se podíval do `city` - a ono je bezcitné: `city` není vyplněno, takže nevím, odkud se ztratilo :(
