### ISSUE TITLE
Lokalizace je zbytečně úporná

### ISSUE THREAD

**Issue by Aidam** [Clevis/ReKola-Public#9]
S novou verzí přišla o dost úpornější snaha o lokalizaci - ocenil bych možnost ji vypnout , nebo aspon ignorovat - zvlášť při půjčování kol, když už zadávám kód kola a vyskočí mi prompt na ruční lokalizaci, radši bych ho zrušil a dovyplnil kód než hledal kde že to jsem. - s novou verzí se ptá znova a znova. 
Obecně mám dojem, že by lokalizace mohla běžet nějak na pozadí, nebo třeba v nějaké liště dole 
Android 403 na HTC one

**Comment by VitekJezek** [comment]
jo, tohle bych skoro řekl, že je bug. @enzy, mrkneš na to, prosím ?

**Comment by enzy** [comment]
Lokalizace je povinná, vyskakování se projevuje pouze u zařízení bez podpory geolokace či při jejím nepovolení.

**Comment by Aidam** [comment]
Já mám lokalizaci povolenou, ale chvíli trvá než se chytí - když teda zapnu aplikaci, dojdu ke kolu a chtěl bych zadat číslo a vyrazit co nejrychleji do školy.. Je opravdu nezbytný se lokalizovat? Kde jsem lze určit z toho, že zadávám kód kola.

**Comment by enzy** [comment]
V plánu je méně otravnější způsob geolokace, který by měl eliminovat snad i tento případ. Dáme vědět až bude online...

**Comment by Aidam** [comment]
Lokalizace je ted sice méně úporná (vůbec), ale nenašla mě při vracení kola snad ani jednou - vždy to skončí tak, že přetahuju mapu podle ujetý trasy na místo kde jsem nakonec zaparkoval (nepraktický). Co takhle přidat nějaký stručný info o stavu lokalizace a / nebo přidat tlačítko lokalizuj k mapě

**Comment by VitekJezek** [comment]
dořešil bych to v rámci #29 (ohledně úpornosti lokalizace), případně #25 (aby se dalo lépe najít poloha)... Tohle pro nyní zavírám...
