### ISSUE TITLE
Datum registrace by mělo začínat spárováním účtu, nikoli odesláním

### ISSUE THREAD

**Issue by filip-jezek** [Clevis/ReKola-Public#92]
Pokud to tak je, omlouvám se, ale ať to můžem říct na helpdesk a říkat lidem to potřebuju potvrdit :)

**Comment by zbycz** [comment]
evidujeme:
- Datum registrace = kdy uživtel potvrdil podmínky o.s.
- Datum spárování platby (může jich být více) = od této doby se počítá expiration-date
- Datum potvrzení provozních podmínek v aplikaci

Myslím, že tak je to správné - datum platby != datum registrace..

**Comment by zbycz** [comment]
ok?
