### ISSUE TITLE
FR: Zakázat vracení kola daleko od domova ;)

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#93]
vzhledem k #80 et al. navrhuju při vracení kola kontrolovat nějaký bounding box, řekněme pár desítek km od domovského města, a vůbec nedovolit vrácení mimo něj; jinak se nám budou hromadit horníci v Příbrami, v Ostravě, v Seattlu a tak podobně ;)

(Toto se liší od "upozornit při vracení mimo zónu" - vrátit kolo mimo zónu by mělo jít, toto by ale měl být tvrdý limit, který pražské kolo neumožní vrátit mimo Prahu a okolí)

Navrhované hard bounding boxy :
Praha => 13.95,50.35,15.06,49.77
Brno => 16.08,49.48,17.19,48.89
Olomouc => 16.87,49.79,17.67,49.42
Pardubice => 15.38,50.24,16.19,49.88

**Comment by mnicky** [comment]
Neviem ako to je momentalne stanovene v podmienkach pouzivania, ale v takom pripade by aj v nich mala byt zmienka o tom, ze sa kola smu vracat iba vramci daneho mesta...

**Comment by Piskvor** [comment]
Jo, tohle je spíš pojistka proti již viděnému "telefon si myslí, že je v Seattlu."

**Comment by zbycz** [comment]
Jsou to dva různé problémy
1. SMSky - to je jasné, už omezujeme hledání adresy na aktuální město
2. Vracení přes mapku v aplikaci. Tam je to chyba toho vracícího screenu - že při lokaci do Seatlu nejsem schopný nazoomovat kam potřebuju. Řešením by bylo omezit "zobrazení mapky" na to město - pokud bychom totiž jen omezili možnost to vrátit, bude to uživatele neskutečně frustrovat.

Vzhledem k tomu, že nativní mobilní app jsou v tomhle ohledu funkční (už jsou hotové, postupně se pouští), navrhuju tohle issue zavřít, souhlas?

**Comment by Piskvor** [comment]
Myslel jsem, že souhlas, ale nesouhlas: někde, nějak se to pořád daří vracet úplně mimo: 
Ludmila [#577] [vráceno 04. 07.]
Kolo s blatníky, nosičem a protišlapnou brzdou
U vjezdu do garáži, u modrých popelnic
city: praha
lokace podle mapy: u Znojma

![staticmap](https://cloud.githubusercontent.com/assets/917239/3552929/f2bb7ce8-08fd-11e4-9c2e-08a82a56f976.png)

**Comment by Piskvor** [comment]
Už dlouho nic, asi opraveno.
