### ISSUE TITLE
Chybny odkaz na podminky ve FAQ na webu

### ISSUE THREAD

**Issue by r0bin-zz** [Clevis/ReKola-Public#94]
Na trance FAQ (http://www.rekola.cz/faq) jsou minimalne na dvou mistech chybne odkazy na pocminky, Misto odkazu http://www.rekola.cz/podminky jsou tam odkazy http://www.rekola.cz/register/podminky  ktere nefunguji. Tipnul bych si, ze to bude pozustatek  presunu z preview do ostre verze.

**Comment by zbycz** [comment]
Opraveno, díky moc. Bylo to nějakým špatným updatem.
