### ISSUE TITLE
Záhadné putování kol v mapě

### ISSUE THREAD

**Issue by rolfovo** [Clevis/ReKola-Public#96]
Tak nevím co se děje s aplikací, ale zdá se, že kola samovolně cestují, aniž by si je někdo vypůjčil. Příklad - kolo Volavka stálo od 9.6. do 12.6. na Náměstí Míru s píchlou duší. A dneska - kouzlo, píchlé kolo stojí na Podolském nábřeží a datum vrácení zůstalo 9.6.
Není někde něco shnilého?

**Comment by zbycz** [comment]
Rozbité to být nemůže - pravděpodobně to upravil admin. Právě v tomto čase totiž servisováno bylo. Kdybys měl další podobné pozorování, klidně napiš.
