### ISSUE TITLE
Rozbitý feed (a druhotně všechno, co ho čte - appky, mapy, Locus, etc.)

### ISSUE THREAD

**Issue by Piskvor** [Clevis/ReKola-Public#99]
V půlce (!) http://moje.rekola.cz/api/bikes/kml se objevuje chybová hláška zformátovaná co HTML:

```
<p>We're sorry! The server encountered an internal error and
was unable to complete your request. Please try again later.</p>
<p><small>error 500</small></p>
```

Po ní už feed nepokračuje, takže není dobře zformovaný. Google mapa si to přechroupe do nějakého polofunkčního formátu, ostatní to rozbije (Locus zůstane viset při importu, androidí appka ReKol rovnou spadne, etc.)

Půjčování a vracení by teoreticky mělo fungovat pořád, ale nějak nemám odvahu to zkusit ;)

**Comment by Glutexo** [comment]
Toho jsem si všimnul už včera, ale přišlo mi to jako přechodná záležitost. Se to pak zase spravilo. Jak to ale vypadá, je to o něco systémovější problém.

**Comment by zbycz** [comment]
Už je to vyřešené (max v průběhu zítřka deploy). Dík za report!
